import turtle

# 绘制佩奇的头
turtle.color("pink")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()

# 绘制佩奇的耳朵
turtle.penup()
turtle.goto(-70, 170)
turtle.pendown()
turtle.color("lightpink")
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
turtle.penup()
turtle.goto(70, 170)
turtle.pendown()
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

# 绘制佩奇的眼睛
turtle.color("white")
turtle.penup()
turtle.goto(-40, 220)
turtle.pendown()
turtle.begin_fill()
turtle.circle(15)
turtle.end_fill()
turtle.penup()
turtle.goto(40, 220)
turtle.pendown()
turtle.begin_fill()
turtle.circle(15)
turtle.end_fill()
turtle.color("black")
turtle.penup()
turtle.goto(-40, 220)
turtle.pendown()
turtle.begin_fill()
turtle.circle(6)
turtle.end_fill()
turtle.penup()
turtle.goto(40, 220)
turtle.pendown()
turtle.begin_fill()
turtle.circle(6)
turtle.end_fill()

# 绘制佩奇的鼻子
turtle.color("pink")
turtle.penup()
turtle.goto(0, 180)
turtle.pendown()
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

# 绘制佩奇的嘴巴
turtle.color("red")
turtle.penup()
turtle.goto(-50, 150)
turtle.pendown()
turtle.pensize(5)
turtle.right(45)
turtle.circle(60, 90)
turtle.penup()
turtle.goto(-50, 150)
turtle.pendown()
turtle.left(90)
turtle.circle(60, 90)

# 绘制佩奇的身体
turtle.color("pink")
turtle.penup()
turtle.goto(-150, -50)
turtle.pendown()
turtle.begin_fill()
turtle.forward(300)
turtle.right(90)
turtle.circle(150, 180)
turtle.right(90)
turtle.forward(300)
turtle.end_fill()

# 绘制佩奇的手臂
turtle.color("lightpink")
turtle.penup()
turtle.goto(-180, 80)
turtle.pendown()
turtle.begin_fill()
turtle.right(45)
turtle.circle(40, 90)
turtle.right(45)
turtle.forward(70)
turtle.right(135)
turtle.circle(40, 90)
turtle.right(45)
turtle.forward(70)
turtle.end_fill()
turtle.penup()
turtle.goto(180, 80)
turtle.pendown()
turtle.begin_fill()
turtle.right(180)
turtle.right(45)
turtle.circle(-40, 90)
turtle.right(45)
turtle.forward(70)
turtle.right(135)
turtle.circle(-40, 90)
turtle.right(45)
turtle.forward(70)
turtle.end_fill()

# 绘制佩奇的腿
turtle.color("lightpink")
turtle.penup()
turtle.goto(-100, -200)
turtle.pendown()
turtle.begin_fill()
turtle.right(45)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(45)
turtle.forward(70)
turtle.right(45)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.end_fill()
turtle.penup()
turtle.goto(100, -200)
turtle.pendown()
turtle.begin_fill()
turtle.right(180)
turtle.right(45)
turtle.forward(-100)
turtle.right(90)
turtle.forward(-100)
turtle.right(45)
turtle.forward(-70)
turtle.right(45)
turtle.forward(-100)
turtle.right(90)
turtle.forward(-100)
turtle.right(45)
turtle.forward(-100)
turtle.end_fill()

turtle.done()
